global:
  scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['20.115.35.168:9093']

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['20.115.35.168:9100']
  - job_name: 'node_exporter_metrics for slaves'
    scrape_interval: 5s
    static_configs:
      - targets: ['13.92.130.101:9100']

